export const items = [
  {
    id: Math.random(),
    title: "وجبة فطار",
    desc: "المكونات: بيض + عيش توست + ملح + فلفل",
    price: "30 جنيه",
    category: "فطار",
    imgUrl: "01.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة فطار صحي",
    desc: " المكونات: كورن فليكس + لبن",
    price: "35 جنيه",
    category: "فطار",
    imgUrl: "02.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة الغداء الأولى",
    desc: "المكونات: نودلز حارة + خضروات + صوص",
    price: "25 جنيه",
    category: "غداء",
    imgUrl: "03.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة الغداء الثانية",
    desc: "المكونات: صلصة + زيتون + خضروات + ميكس لحوم و فراخ",
    price: "55 جنيه",
    category: "غداء",
    imgUrl: "04.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة العشاء الأولى",
    desc: "المكونات: شراح لحم + خس + بصل + طماطم + جبنة شيدر مع فرنش فرايز",
    price: "70 جنيه",
    category: "عشاء",
    imgUrl: "05.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء للعائلة",
    desc: "المكونات: سمك مشوي + سلطات + طحينة  ",
    price: "100 جنيه",
    category: "عشاء",
    imgUrl: "06.jpg",
  },
  {
    id: Math.random(),
    title: "مقبلات",
    desc: "المكونات: بطاطس محمرة بالخلطة السرية  ",
    price: "20 جنيه",
    category: "مقبلات",
    imgUrl: "07.jpg",
  },
];
